### ISSUE TITLE
Support --config with Config File

### ISSUE THREAD

**Issue by DukeManh** [BeAmazedVariable/TS-SSG#12]
Users want to be able to specify all of their SSG options in a JSON formatted configuration file instead of having to pass them all as command line arguments every time. For example, consider the following config file, ./ssg-config.json:
```
{
  "input": "./site",
  "output": "./build",
  "stylesheet": "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css",
  "lang": "fr"
}
```
A user could run the SSG by doing the following:

`ssg --config ./ssg-config.json`

The config file option means we can have a much shorter command, and instead store our options in a file.

**Comment by tpmai22** [comment]
Hi Duke,
It is my honor to get your brilliant help on my project. I would love to do the same thing on your repo if you allowed me to ?

**Comment by DukeManh** [comment]
Please go ahead. Thank you James.
