### ISSUE TITLE
Remove unused dependency

### ISSUE THREAD

**Issue by humphd** [BeAmazedVariable/TS-SSG#3]
It looks like a typo introduced an unused dependency: https://github.com/BeAmazedVariable/TS-SSG/blob/main/package.json#L31.  You should remove this.

**Comment by tpmai22** [comment]
Closed by [6f20f71](https://github.com/BeAmazedVariable/TS-SSG/commit/6f20f71a78dcff2318f039d7b84e10d436e230c9)
